### ISSUE TITLE
My osu!lazer crashed all the time for none reason. 

### ISSUE THREAD

**Issue by miyucode** [ppy/osu-resources#123]
I don't know why but i can't start osu!lazer, if i start osu!lazer, he crashed and sometime, give me a BSoD, my processor is a Intel Celeron N3350 of 1,10GhZ, thanks you for helping, Miyu.

**Comment by miyucode** [comment]
I don't know why but i can't start osu!lazer, if i start osu!lazer, he crashed and sometime, give me a BSoD, my processor is a Intel Celeron N3350 of 1,10GhZ, thanks you for helping, Miyu.

**Comment by peppy** [comment]
We cannot do anything with this information, sorry. Please re-read the issue template and include all information required, then comment on this issue so we can consider re-opening it.

**Comment by miyucode** [comment]
where is the template then?

**Comment by frenzibyte** [comment]
[Here](https://github.com/ppy/osu/issues/new?assignees=&labels=&template=01-bug-issues.md) is where you should be reporting issues, follow the template in there.
