### ISSUE TITLE
Update the flag icon to the latest (not Twemoji)

### ISSUE THREAD

**Issue by Kotoki1337** [ppy/osu-resources#189]
Sorry for the issue here, but osu!lazer's flag resources are still four years old.

Flags of many countries wrong like China's:
**osu-web (old)**:
![CN.png](https://raw.githubusercontent.com/ppy/osu-web/fdfa312a3fc7fa82b132b099dd4425471e6a1e07/public/images/flags/CN.png)
**osu-resources (lazer):**:
![CN.png](https://github.com/ppy/osu-resources/blob/master/osu.Game.Resources/Textures/Flags/CN.png?raw=true)

Also the flags of many countries are missing like BL:
**osu-web (twemoji)**:
![image](https://user-images.githubusercontent.com/35394151/163682059-264c9a38-5f24-4c73-9037-35028d8a5e65.png)
**osu-web (old)**:
![BL.png](https://raw.githubusercontent.com/ppy/osu-web/fdfa312a3fc7fa82b132b099dd4425471e6a1e07/public/images/flags/BL.png)
**osu-resources (lazer)**:
There's no BL flag in osu-resources.
![image](https://user-images.githubusercontent.com/35394151/163682200-5e1de1af-fa65-4936-ab11-e716c9e78d98.png)

I know that osu-web uses twemoji and that osu-lazer is planning to use twemoji, but I think we should update the flag icon in osu-resources to the latest version. Because some countries are very strict about flags and this has resulted in some tournament using osu!lazer as the osu!tourney client cant not being broadcast or uploading video in their countries because they have the wrong flags.

So I think should make a simple fix like update the flag icon of osu-resources to the latest version as the old osu! design? Because we have repaired some of them before and have also filled in most of the countries or regions that did not have flags.

**Comment by bdach** [comment]
i have no idea what the "latest version" is supposed to mean here. updating the icons is an eternal low priority item in my backlog, but if they are updated, then they will be updated to whatever the website is using. is there something i'm not aware of?

**Comment by Kotoki1337** [comment]
I'm sorry I didn't express it clearly, the latest version I was referring to was the last update of the old design before it was replaced to twemoji. Because some of the flags were wrong, there was an active issue asking for changes to the flags, and it was basically that issue that was pushing for the old design to be updated with the wrong flags.

For example, the latest public version in osu-web should be: [osu-web/public/images/flags(fdfa312a3fc7fa82b132b099dd4425471e6a1e07)](https://github.com/ppy/osu-web/tree/fdfa312a3fc7fa82b132b099dd4425471e6a1e07/public/images/flags)

**Comment by bdach** [comment]
i personally am only willing to update the flags to what web is using, i'm not going to use anything different. if there's a problem with twemoji then raise it up with twemoji or with web first.

**Comment by Kotoki1337** [comment]
> then they will be updated to whatever the website is using right now (which is twemoji)

It doesn't look like that, osu-web, osu-wiki, osu-lazer(in osu-resources) all have their own flag folders and they are different

**Comment by Kotoki1337** [comment]
Alright, the flag for osu-resources hasn't been updated in three years, it really hasn't been updated in sync with everything else. I saw the osu-lazer issue about twemoji and it has priority, but it doesn't look active and I don't know when it will be done. I could actually send a pr to help with the update, but osu-resources need the 2x version of the png, I don't have the latest version of 2x, and I know you guys should have a private repo to put those things in, @flyte said something about this in osu-web's issues. So I think we should update the current version of the old design before osu-lazer dosen't update to twemoji. Because some of the flag errors are really fatal and cause a lot of tough issues. I understand your workflow, this is just my opinion, I 
dont have the needed version of 2x so I can't do anything, so I can only post an issue here. That's it.

**Comment by peppy** [comment]
To confirm, updating to use the latest (twemoji + filter) version is the only way forward.

**Comment by frenzibyte** [comment]
For reference, updating to twemoji is tracked in https://github.com/ppy/osu/issues/16422.

**Comment by peppy** [comment]
Let's track there
