### ISSUE TITLE
Client translation updates from crowdin seem to be skipping some files

### ISSUE THREAD

**Issue by bdach** [ppy/osu-resources#239]
Original mention: https://github.com/ppy/osu/issues/21953#issuecomment-1368063818

https://github.com/ppy/osu-resources/blob/master/osu.Game.Resources/Localisation/GraphicsSettings.hu.resx has not been changed since June 28, although there have been several updates to the localisations since then (see history here: https://github.com/ppy/osu-resources/commits/master/osu.Game.Resources/Localisation)

Or there's something about crowdin I'm not understanding. Dunno

**Comment by peppy** [comment]
The update process is definitely pulling down the file:

![iTerm2 2023-01-10 at 04 43 41](https://user-images.githubusercontent.com/191335/211463898-d28ac7b9-8621-464a-8618-103193b04306.png)

It could just be that it hasn't been run since the translations were added? I'll try running again now.

**Comment by peppy** [comment]
This seems to have updated with https://github.com/ppy/osu-resources/pull/240, so let's call this one resolved.
