### ISSUE TITLE
Belgium flag is not stretched

### ISSUE THREAD

**Issue by Sclafus** [ppy/osu-resources#259]
Hello everyone, 
just noticed that the Belgian flag is not stretched.
![Belgian flag](https://raw.githubusercontent.com/ppy/osu-resources/master/osu.Game.Resources/Textures/Flags/BE.png)
French flag for reference:
![French flag](https://raw.githubusercontent.com/ppy/osu-resources/master/osu.Game.Resources/Textures/Flags/FR.png)

On osu! web, it is noticeable if you were wandering.
![image](https://github.com/ppy/osu-resources/assets/31241607/1eb9c76b-3ac5-4b61-aa14-8ba091497425)

**Comment by bdach** [comment]
This is intentional. The flags are derived from twitter's [twemoji](https://github.com/twitter/twemoji) project. The website uses the same icons. The same thing goes for flags of Switzerland, Nepal, the Vatican, etc.

If you have a problem with this, take it to upstream.

**Comment by Sclafus** [comment]
While I agree with your point of view, I think that it looks very out of place on the osu! website

**Comment by bdach** [comment]
Relevant upstream thread: https://github.com/twitter/twemoji/pull/520

**Comment by MaxTechnics** [comment]
While it indeed looks off. Belgiums flag actually is a near square aspect ratio. Though usually disregarded in most graphics.

**Comment by Sclafus** [comment]
Thanks everyone, I get it now, it is an official thing and not an arbitrary decision
