### ISSUE TITLE
approach circle 1:1 resolution

### ISSUE THREAD

**Issue by Agrrox** [ppy/osu-resources#40]
It seems like sprite of osu approach circle has been re-used and it is 252 × 256.
But for clarity and for future use of skinning it should better to be 256 × 256.
Also when skinning, It seems like that the texture of approarch circle is not centered either.

**Comment by peppy** [comment]
We are reworking how textures work in skinning, to the point where texture sizes are not important (the sizes will be defined by the containers of the textures/sprites). Not sure how worthwhile changing this is.

On top of that, it is highly likely these sprites will be replaced by a shader/drawable-based implementation before release.
