### ISSUE TITLE
Several flags have incorrect details

### ISSUE THREAD

**Issue by Poyo-SSB** [ppy/osu-resources#43]
There are a few details that hold cultural value in some flags that were ignored for the purpose of designing nicer images. Notably:

* China (`CN`): The four small stars should be pointed towards the larger star. The 2016 Summer Olympics at Rio [failed to adhere to this](http://time.com/4445373/rio-2016-olympics-china-wrong-flags/).
* Ethiopia (`ET`): The [emblem](https://en.wikipedia.org/wiki/Flag_of_Ethiopia#Emblem) in the center of the flag is quite heavily emphasized by the government.
* Micronesia (`FM`): The four stars should be pointing in each of the four cardinal directions.
* United Kingdom (`GB`): The red saltire of St. Patrick should be offset. This isn't really offensive, but it does look [silly to ignore](http://www.gizmodo.co.uk/2016/09/the-british-flag-at-the-olympics-was-totally-wrong-and-no-one-is-fixing-it-for-the-paralympics/).
* Guyana (`GY`): While unlikely to cause offense, this representation of the flag is really poorly made. All the triangles should be vertically centered and the white/yellow triangles should extend to the right side of the flag.
* Israel (`IL`): As a religious symbol representing (in the modern day) Judaism, it's probably best to not stylize the Star of David.
* India (`IN`): As a spiritual symbol, the Ashoka Chakra (the 24-spoked wheel) should probably not be simplified.
* **Cambodia (`KH`): This one's simply incorrect. The central band should be red and the outer bands should be blue, not vice versa.**
* Comoros (`KM`): As a symbol of Islam, the crescent (and stars) should probably not be distorted as they are.
* South Korea (`KR`): The four black [trigrams](https://en.wikipedia.org/wiki/Bagua) represent national values, but have been reduced to meaningless double lines.
* **Sri Lanka (`LK`): The golden lion on the left side of the flag is completely missing.**
* Morocco (`MA`): As with Israel, the pentagram is a religious symbol (Seal of Solomon) and should not be simplified.
* **Mauritania (`MR`): The red stripes on the top and bottom are completely missing.**
* **Maldives (`MV`): The center is completely incorrect. It should not be blue, it should be green.**

Generally, the star-and-crescent symbol is depicted inconsistently, sometimes using a circle in place of the star.

There are certain similar details that are also missing which I've excluded because they're not culturally significant. Most of the ones I *have* listed are also probably insignificant as well, so this entire issue is not a big problem.

**Comment by PythonTryHard** [comment]
I would probably bodge this. I'm bored anyway

**Comment by peppy** [comment]
Please file this issue against [osu-web](https://github.com/ppy/osu-web), where we have already begun to fix flags on a per-flag basis in cases people actually care. Note that you will need to re-checck those that you mentioned as I believe a few may be fixed.
