### ISSUE TITLE
Replace the rank icons with new ones

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-resources#57]
according to the new design available on the website

**Comment by peppy** [comment]
Is this being followed up by a PR?

**Comment by TPGPL** [comment]
not planned, but i think i can do that

**Comment by peppy** [comment]
Just trying to avoid clutter of tiny issues being filed for tasks like this which would generally be considered parts of larger design refreshes (lazer is behind on many designs; sprite updates would likely be batched with other changes).
