### ISSUE TITLE
Easy mod icon does not match osu-web

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-resources#92]

**Comment by peppy** [comment]
Are you sure it's just the easy mod? Last I checked a lot were out of date because we don't have a method of exporting/importing the glyphs in their current "font" state.

**Comment by sr229** [comment]
Is this still the case? Last I checked they seem to be in sync relatively.

**Comment by bdach** [comment]
![2021-06-18-143031_2477x569_scrot](https://user-images.githubusercontent.com/20418176/122561142-ca467980-d041-11eb-8fb4-23e158a21362.png)

**Comment by MaxTechnics** [comment]
I'm checking and comparing the mods. Will edit as check progresses
NF: To check
EZ: Different
HT: To check
AT: To check (irrelevant?)
CN: To check (irrelevant?)
RL: To check (irrelevant?)
HR: Match
SD: Match
PF: To check
DT: Match
NC: Match
HD: Match
FL: Match
